# Generated by Django 5.1.7 on 2025-03-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixorin_dns', '0002_alter_dnsrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
