# Generated by Django 5.1.7 on 2025-03-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixorin_dns', '0003_licensekey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
