# Generated by Django 5.1.7 on 2025-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixorin_dns', '0005_alter_licensekey_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='is_active',
        ),
    ]
