# Generated by Django 5.1.7 on 2025-03-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixorin_dns', '0006_remove_licensekey_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
